name: Build Action
on:
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: ls ${{ github.workspace }}
      - name: Configure conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          environment-file: env.yaml
          activate-environment: academic
          auto-activate-base: false
      - name: Test conda
        run: |
          which python
          conda activate academic
          which python
